# Generated by Django 3.0.6 on 2020-08-01 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
